[default]
hostname = "steamdeck"

local_playlists = "/Users/david/Library/Application Support/RetroArch/playlists"
local_bios = "/Users/david/Library/Application Support/RetroArch/system"
local_roms = "/Users/david/Dropbox/Software/Roms"
local_roms_alt= "/Users/david/Library/CloudStorage/Dropbox/Software/Roms"
local_cores = "/Users/david/Library/Application Support/RetroArch/cores"
local_thumbnails = "/Users/david/Library/Application Support/RetroArch/thumbnails"
local_cores_suffix = ".dylib"

remote_playlists = "/home/deck/.var/app/org.libretro.RetroArch/config/retroarch/playlists"
remote_bios = "/home/deck/Emulation/bios"
remote_roms = "/run/media/deck/Steamdeck/roms"
remote_cores = "/home/deck/.var/app/org.libretro.RetroArch/config/retroarch/cores"
remote_thumbnails = "/home/deck/.var/app/org.libretro.RetroArch/config/retroarch/thumbnails"
remote_cores_suffix = ".so"

[[playlists]]
name = "Atari - 2600.lpl"
local_folder = "Atari - 2600"
remote_folder = "atari2600"
core_path =  "prosystem_libretro"
core_name = "Atari - 2600 (Stella)"


[[playlists]]
name = "Atari - 7800.lpl"
local_folder = "Atari - 7800"
remote_folder = "atari7800"
core_path =  "prosystem_libretro"
core_name = "Atari - 7800 (ProSystem)"

[[playlists]]
name = "Atari - Lynx.lpl"
local_folder = "Atari - Lynx"
remote_folder = "atarilynx"
core_path = "handy_libretro"
core_name = "Atari - Lynx (Handy)"

[[playlists]]
name = "Atari - Jaguar.lpl"
local_folder = "Atari - Jaguar"
remote_folder = "atarijaguar"
core_path =  "virtualjaguar_libretro"
core_name =  "Atari - Jaguar (Virtual Jaguar)"

[[playlists]]
name = "FBNeo - Arcade Games.lpl"
local_folder = "SNK - Neo Geo"
remote_folder = "neogeo"
core_path  = "fbneo_libretro"
core_name = "Arcade (FinalBurn Neo)"

[[playlists]]
name = "MAME 2003-Plus.lpl"
local_folder = "MAME 2003-Plus"
remote_folder = "mame"
core_path = "mame2003_plus_libretro"
core_name = "Arcade (MAME 2003-Plus)"

[[playlists]]
name = "Nintendo - Game Boy Advance.lpl"
local_folder = "Nintendo - Game Boy Advance"
remote_folder = "gba"
core_path =  "mgba_libretro"
core_name =  "Nintendo - Game Boy Advance (mGBA)"

[[playlists]]
name = "Nintendo - Game Boy Color.lpl"
local_folder = "Nintendo - Game Boy Color"
remote_folder = "gbc"
core_path =  "gambatte_libretro"
core_name =  "Nintendo - Game Boy / Color (Gambatte)"

[[playlists]]
name = "Nintendo - Game Boy.lpl"
local_folder = "Nintendo - Game Boy"
remote_folder = "gb"
core_path =  "gambatte_libretro"
core_name =  "Nintendo - Game Boy / Color (Gambatte)"

[[playlists]]
name = "Nintendo - GameCube.lpl"
local_folder = "Nintendo - GameCube"
remote_folder = "gamecube"
core_path =  "dolphin_libretro"
core_name = "Nintendo - GameCube/ Wii (Dolphin)"

[[playlists]]
name = "Nintendo - Nintendo 64.lpl"
local_folder = "Nintendo - Nintendo 64"
remote_folder = "n64"
core_path = "mupen64plus_next_libretro"
core_name = "Nintendo - Nintendo 64 (Mupen64Plus-Next)"

[[playlists]]
name = "Nintendo - Nintendo DS.lpl"
local_folder = "Nintendo - Nintendo DS"
remote_folder = "nds"
core_path = "melonds_libretro"
core_name = "Nintendo - DS (melonDS)"

[[playlists]]
name = "Nintendo - Nintendo Entertainment System.lpl"
local_folder = "Nintendo - Nintendo Entertainment System"
remote_folder = "nes"
core_path =  "mesen_libretro"
core_name =  "Nintendo - NES / Famicom (Mesen)"

[[playlists]]
name = "Nintendo - Super Nintendo Entertainment System.lpl"
local_folder = "Nintendo - Super Nintendo Entertainment System"
remote_folder = "snes"
core_path  = "snes9x_libretro"
core_name =  "Nintendo - SNES / SFC (Snes9x)"

[[playlists]]
name = "Nintendo - Virtual Boy.lpl"
local_folder = "Nintendo - VirtualBoy"
remote_folder = "virtualboy"
core_path =  "mednafen_vb_libretro"
core_name =  "Nintendo - Virtual Boy (Beetle VB)"

[[playlists]]
name = "Nintendo - Wii.lpl"
local_folder = "Nintendo - Wii"
remote_folder = "wii"
core_path =  "dolphin_libretro"
core_name = "Nintendo - GameCube/ Wii (Dolphin)"

[[playlists]]
name = "PC Engine - TurboGrafx.lpl"
local_folder = "PC Engine - TurboGrafx"
remote_folder = "pcengine"
core_path =  "mednafen_pce_libretro"
core_name =  "PC Engine / SuperGrafx / CD (Beetle PCE)"

[[playlists]]
name = "Sega - 32X.lpl"
local_folder = "Sega - 32X"
remote_folder = "sega32x"

[[playlists]]
name = "Sega - Dreamcast.lpl"
local_folder = "Sega - Dreamcast"
remote_folder = "dreamcast"
core_path =  "picodrive_libretro"
core_name = "Sega - MS/GG/MD/CD/32X (PicoDrive)"

[[playlists]]
name = "Sega - Game Gear.lpl"
local_folder = "Sega - Game Gear"
remote_folder = "gamegear"
core_path =  "picodrive_libretro"
core_name = "Sega - MS/GG/MD/CD/32X (PicoDrive)"

[[playlists]]
name = "Sega - Master System.lpl"
local_folder = "Sega - Master System"
remote_folder = "mastersystem"
core_path =  "picodrive_libretro"
core_name = "Sega - MS/GG/MD/CD/32X (PicoDrive)"

[[playlists]]
name = "Sega - Mega Drive.lpl"
local_folder = "Sega - Mega Drive"
remote_folder = "megadrive"
core_path =  "picodrive_libretro"
core_name = "Sega - MS/GG/MD/CD/32X (PicoDrive)"

[[playlists]]
name = "Sega - Saturn.lpl"
local_folder = "Sega - Saturn"
remote_folder = "saturn"
core_path  ="mednafen_saturn_libretro"
core_name =  "Sega - Saturn (Beetle Saturn)"

[[playlists]]
name = "Sony - PlayStation.lpl"
local_folder = "Sony - PlayStation"
remote_folder = "psx"
core_path  = "mednafen_psx_libretro"
core_name = "Sony - PlayStation (Beetle PSX)"

[[playlists]]
name = "Sony - PlayStation 2.lpl"
local_folder = "Sony - PlayStation 2"
remote_folder = "ps2"
core_path =  "play_libretro"
core_name = "Sony - PlayStation 2 (Play!)"

[[playlists]]
name = "Sony - PlayStation Portable.lpl"
local_folder = "Sony - PlayStation Portable"
remote_folder = "psp"
core_path = "ppsspp_libretro"
core_name = "Sony - PlayStation Portable (PPSSPP)"

[[playlists]]
name = "DOOM.lpl"
local_folder = "ID - Doom"
remote_folder = "doom"
core_path = "prboom_libretro"
core_name = "Doom (PrBoom)"

[[playlists]]
name = "Cannonball.lpl"
local_folder = "Cannonball"
remote_folder = "cannonball"
core_path = "cannonball_libretro"
core_name = "Cannonball"
