name: Build Executables

on:
  workflow_dispatch:  # This allows the workflow to be triggered manually

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile retrosync.py

      - name: Get Version
        id: get_version
        shell: powershell
        run: |
          $content = Get-Content VERSION -Raw
          echo "::set-output name=file_content::$content"

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-executable
          path: ./dist/retrosync.exe

      - name: Upload Windows executable
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.file_content }}
          files: ./dist/retrosync.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile retrosync.py

      - name: Get Version
        id: get_version
        run: |
          current_version=$(cat VERSION)
          echo "::set-output name=current_version::$current_version"

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-executable
          path: ./dist/retrosync

      - name: Upload macOS executable
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.current_version }}
          files: ./dist/retrosync
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
