name: Lint Python Code with Ruff

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff Linter
        run: |
          ruff . --fix
          
      - name: Upload Ruff results as artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: ruff-lint-results
          path: .

